# Generated by Django 5.1.6 on 2025-02-18 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
